sudo: required

notifications:
  email: false

language: python
cache: pip

python:
- "2.7"

env:
- MODE=mitogen MITOGEN_TEST_DISTRO=debian
- MODE=mitogen MITOGEN_TEST_DISTRO=centos
- MODE=debops
- MODE=ansible ANSIBLE_VERSION=2.4.3.0 MITOGEN_TEST_DISTRO=debian
- MODE=ansible ANSIBLE_VERSION=2.5.0 MITOGEN_TEST_DISTRO=centos

install:
- pip install -r dev_requirements.txt

script:
- ${TRAVIS_BUILD_DIR}/.travis/${MODE}_tests.sh

services:
  - docker
