sudo: required

notifications:
  email: false

language: python
cache: pip

python:
- "2.7"

env:
- MODE=mitogen
- MODE=debops
- MODE=ansible ANSIBLE_VERSION=2.4.3.0
- MODE=ansible ANSIBLE_VERSION=2.5.0

install:
- pip install -r dev_requirements.txt

script:
- ${TRAVIS_BUILD_DIR}/.travis/${MODE}_tests.sh

services:
  - docker
